pipelines:
  - name: sometest
    steps:
    - name: step1
      type: Bash
      execution:
        onExecute:
          - sleep 1h

    - name: step2
      type: Bash
      configuration:
        inputSteps:
          - name: step1
      execution:
        onExecute:
          - sleep 1h

    - name: step3
      type: Bash
      configuration:
        inputSteps:
          - name: step2
      execution:
        onExecute:
          - sleep 1h

    - name: step4
      type: Bash
      configuration:
        inputSteps:
          - name: step3
      execution:
        onExecute:
          - sleep 1h

    - name: step5
      type: Bash
      configuration:
        inputSteps:
          - name: step4
      execution:
        onExecute:
          - sleep 1h

    - name: step6
      type: Bash
      configuration:
        inputSteps:
          - name: step5
      execution:
        onExecute:
          - sleep 1h

    - name: step7
      type: Bash
      configuration:
        inputSteps:
          - name: step6
      execution:
        onExecute:
          - sleep 1h

    - name: step8
      type: Bash
      configuration:
        inputSteps:
          - name: step7
      execution:
        onExecute:
          - sleep 1h

    - name: step9
      type: Bash
      configuration:
        inputSteps:
          - name: step8
      execution:
        onExecute:
          - sleep 1h